export const heroImage = "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600&q=80";

export const industries = [
  { name: "Energy & Power", img: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&q=80", count: "340+" },
  { name: "Healthcare", img: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=80", count: "280+" },
  { name: "Technology", img: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&q=80", count: "420+" },
  { name: "Financial Services", img: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&q=80", count: "225+" },
  { name: "Consumer Goods", img: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400&q=80", count: "310+" },
  { name: "ESG & Sustainability", img: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&q=80", count: "380+" },
  { name: "Automotive", img: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400&q=80", count: "190+" },
  { name: "Agriculture", img: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&q=80", count: "265+" },
  { name: "Manufacturing", img: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&q=80", count: "195+" },
  { name: "Aerospace", img: "https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?w=400&q=80", count: "145+" },
  { name: "Mining & Metals", img: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&q=80", count: "130+" },
  { name: "Real Estate", img: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&q=80", count: "175+" },
];

export const reports = [
  {
    slug: "india-renewable-energy-2026", title: "India Renewable Energy Market 2026",
    code: "ME-ENR-042", price: 4950, pages: 295, cagr: "12.3%", period: "2025–2031", cat: "Energy", badge: "Bestseller", size: "$48.2B", baseYear: "2025",
    img: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=500&q=80",
    desc: "Comprehensive analysis of India's renewable energy landscape covering solar PV, wind, biomass, and green hydrogen. Includes state-level policy mapping, corporate PPA trends, and 500GW capacity roadmap.",
    companies: ["Adani Green Energy", "Tata Power", "NTPC Ltd", "ReNew Energy", "Suzlon Energy"],
    domains: ["adanigreenenergy.com", "tatapower.com", "ntpc.co.in", "renew.com", "suzlon.com"],
    overview: "India's renewable energy market is projected to grow from $48.2B in 2025 to $98.7B by 2031, driven by government targets of 500GW renewable capacity, declining solar and wind costs, green hydrogen initiatives, and increasing corporate PPA adoption across major industrial consumers.",
    segments: ["Solar PV", "Wind (Onshore & Offshore)", "Biomass & Biogas", "Small Hydro", "Green Hydrogen"],
    regions: ["North India", "Western India", "Southern India", "Eastern India", "Offshore"],
    toc: ["1. Market Overview & Methodology", "2. Executive Summary", "3. Market Dynamics", "4. Segmentation by Source", "5. Segmentation by Application", "6. Regional Analysis (State-Level)", "7. Competitive Landscape", "8. Company Profiles (12 Companies)", "9. ESG Impact Assessment", "10. Regulatory Framework", "11. Investment Outlook", "12. Appendix"],
  },
  {
    slug: "green-finance-market", title: "Green Finance Market",
    code: "ME-FIN-008", price: 4500, pages: 240, cagr: "22.4%", period: "2025–2031", cat: "Financial", badge: null, size: "$5.2T", baseYear: "2025",
    img: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&q=80",
    desc: "Global green finance intelligence covering green bonds, sustainability-linked loans, and ESG equity flows. Regulatory analysis across EU Taxonomy, ISSB, and emerging market frameworks.",
    companies: ["BlackRock", "BNP Paribas", "HSBC", "Goldman Sachs", "J.P. Morgan"],
    domains: ["blackrock.com", "bnpparibas.com", "hsbc.com", "goldmansachs.com", "jpmorgan.com"],
    overview: "The global green finance market is expanding from $5.2T in 2025 to an estimated $18.4T by 2031 at 22.4% CAGR, driven by EU Taxonomy adoption, sovereign green bond programs, mandatory climate disclosures, and institutional investor ESG mandates.",
    segments: ["Green Bonds", "Sustainability-Linked Loans", "ESG Equity Funds", "Social Bonds", "Transition Finance"],
    regions: ["Europe", "North America", "Asia-Pacific", "Middle East & Africa"],
    toc: ["1. Market Overview", "2. Executive Summary", "3. Market Dynamics", "4. Segmentation by Instrument", "5. Segmentation by Issuer", "6. Regional Analysis", "7. Competitive Landscape", "8. Company Profiles", "9. ESG Assessment", "10. Regulatory Framework", "11. Appendix"],
  },
  {
    slug: "carbon-credit-trading", title: "Global Carbon Credit Trading Market",
    code: "ME-ENV-028", price: 4750, pages: 310, cagr: "22.4%", period: "2025–2031", cat: "Sustainability", badge: "New", size: "$2.8B", baseYear: "2025",
    img: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=500&q=80",
    desc: "Deep-dive into voluntary and compliance carbon markets worldwide. Covers credit pricing dynamics, Article 6 implementation, nature-based solutions, and corporate net-zero demand.",
    companies: ["South Pole", "Verra", "Gold Standard", "Climate Impact X", "Xpansiv"],
    domains: ["southpole.com", "verra.org", "goldstandard.org", "climateimpactx.com", "xpansiv.com"],
    overview: "The voluntary carbon credit market reached $2.8B in 2025 and is projected to grow to $15.2B by 2031, driven by corporate net-zero commitments, Article 6 implementation, and evolving compliance mechanisms.",
    segments: ["Voluntary Credits", "Compliance Markets", "Carbon Offsets", "Removal Credits", "Nature-Based Solutions"],
    regions: ["Global", "Europe", "North America", "Asia-Pacific", "Latin America"],
    toc: ["1. Market Overview", "2. Executive Summary", "3. Market Dynamics", "4. Segmentation by Credit Type", "5. Segmentation by End-Use", "6. Regional Analysis", "7. Competitive Landscape", "8. Company Profiles", "9. ESG Assessment", "10. Appendix"],
  },
  {
    slug: "e-waste-recycling", title: "E-Waste Recycling Market",
    code: "ME-ENV-003", price: 4250, pages: 260, cagr: "14.3%", period: "2025–2031", cat: "Sustainability", badge: "Trending", size: "$65.8B", baseYear: "2025",
    img: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=500&q=80",
    desc: "Market intelligence on the global e-waste recycling value chain. Tracks EPR regulation, critical mineral recovery economics, circular economy mandates across 30+ countries.",
    companies: ["Sims Metal", "Umicore", "Veolia", "Stena Recycling", "Boliden"],
    domains: ["simsltd.com", "umicore.com", "veolia.com", "stenarecycling.com", "boliden.com"],
    overview: "The global e-waste recycling market is projected to grow from $65.8B in 2025 to $148.2B by 2031, fueled by tightening EPR regulations, critical mineral recovery demand, and circular economy mandates.",
    segments: ["Consumer Electronics", "IT & Telecom", "Industrial Electronics", "Medical Devices", "Batteries"],
    regions: ["Asia-Pacific", "Europe", "North America", "Rest of World"],
    toc: ["1. Market Overview", "2. Executive Summary", "3. Market Dynamics", "4. Segmentation by Source", "5. Segmentation by Material", "6. Regional Analysis", "7. Competitive Landscape", "8. Company Profiles", "9. ESG Assessment", "10. Appendix"],
  },
  {
    slug: "wind-turbine-market", title: "Wind Turbine Market",
    code: "ME-ENR-015", price: 4750, pages: 310, cagr: "9.1%", period: "2025–2031", cat: "Energy", badge: null, size: "$98.7B", baseYear: "2025",
    img: "https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=500&q=80",
    desc: "Global wind turbine market covering onshore, fixed offshore, and floating offshore segments. Includes OEM competitive analysis, supply chain assessment, and government auction pipelines.",
    companies: ["Vestas", "Siemens Gamesa", "GE Vernova", "Goldwind", "Nordex"],
    domains: ["vestas.com", "siemensgamesa.com", "gevernova.com", "goldwind.com", "nordex-online.com"],
    overview: "The global wind turbine market is set to grow from $98.7B in 2025 to $175.3B by 2031, driven by offshore wind expansion, repowering, and government renewable targets.",
    segments: ["Onshore", "Offshore (Fixed)", "Offshore (Floating)", "Small Wind"],
    regions: ["Europe", "Asia-Pacific", "North America", "Latin America", "MEA"],
    toc: ["1. Market Overview", "2. Executive Summary", "3. Market Dynamics", "4. Segmentation by Installation", "5. Segmentation by Capacity", "6. Regional Analysis", "7. Competitive Landscape", "8. Company Profiles", "9. ESG Assessment", "10. Appendix"],
  },
  {
    slug: "industrial-robotics", title: "Industrial Robotics Market",
    code: "ME-TEC-021", price: 4500, pages: 295, cagr: "11.7%", period: "2025–2031", cat: "Technology", badge: null, size: "$22.1B", baseYear: "2025",
    img: "https://images.unsplash.com/photo-1581091226033-d5c48150dbaa?w=500&q=80",
    desc: "Analysis of articulated, collaborative, SCARA, and delta robots across automotive, electronics, and logistics. Tracks AI integration, Industry 4.0, and labor-shortage automation cycles.",
    companies: ["Fanuc", "ABB", "KUKA", "Yaskawa", "Universal Robots"],
    domains: ["fanuc.com", "abb.com", "kuka.com", "yaskawa.com", "universal-robots.com"],
    overview: "The industrial robotics market is expected to grow from $22.1B in 2025 to $43.8B by 2031, driven by labor shortages, Industry 4.0, collaborative robots, and AI-enhanced automation.",
    segments: ["Articulated", "Collaborative (Cobots)", "SCARA", "Delta", "Cartesian"],
    regions: ["Asia-Pacific", "Europe", "North America", "Rest of World"],
    toc: ["1. Market Overview", "2. Executive Summary", "3. Market Dynamics", "4. Segmentation by Type", "5. Segmentation by Industry", "6. Regional Analysis", "7. Competitive Landscape", "8. Company Profiles", "9. ESG Assessment", "10. Appendix"],
  },
  {
    slug: "onshore-drilling-market", title: "Global Onshore Drilling Market",
    code: "ME-ENR-058", price: 5250, pages: 298, cagr: "5.70%", period: "2026–2031", cat: "Energy", badge: "New", size: "$85.4B", baseYear: "2025",
    img: "https://images.unsplash.com/photo-1513828583688-c52646db42da?w=500&q=80",
    desc: "Comprehensive analysis of global onshore drilling covering conventional land rigs, directional/horizontal, and automated/smart drilling. Segmented by rig type, technology, application, and geography. Includes ESG analysis, 12 company profiles, and sustainability strategies.",
    companies: ["SLB (Schlumberger)", "Halliburton Company", "Baker Hughes", "Nabors Industries", "National Oilwell Varco", "Patterson-UTI Energy"],
    domains: ["slb.com", "halliburton.com", "bakerhughes.com", "nabors.com", "nov.com", "patenergy.com"],
    overview: "The Global Onshore Drilling Market size is estimated at USD 85.4 billion in 2026 and is expected to reach USD 112.6 billion by 2031, growing at a CAGR of 5.70% over the forecast period (2026–2031). Rising global energy demand, depletion of shallow conventional reserves, and sustained unconventional resource development across North America and the Middle East are the primary growth drivers. Onshore drilling accounts for approximately 69.5% of total global drilling services revenue, reflecting its structural cost advantage over offshore operations.",
    segments: ["Conventional Land Rigs", "Directional / Horizontal Rigs", "Slim-Hole / Portable Rigs"],
    segmentsByTech: ["Top-Drive Systems", "Conventional Rotary", "Automated & Smart Drilling"],
    segmentsByApp: ["Oil Production Drilling", "Natural Gas Exploration", "Geothermal & Mineral Exploration"],
    regions: ["North America", "Middle East & Africa", "Asia-Pacific", "South America", "Europe"],
    marketConcentration: "Moderate",
    fastestGrowingRegion: "Middle East & Africa",
    largestRegion: "North America",
    keyTakeaways: [
      "By rig type, conventional land rigs commanded the largest share of 58.3% of the 2025 revenue. Moreover, directional and horizontal rigs are expected to grow at the fastest CAGR of 7.73% during the forecast period (2026–2031).",
      "By technology, top-drive systems held the largest market share of 44.6% in 2025. Automated and smart drilling technology is projected to grow at the fastest CAGR of 9.4% during the forecast period (2026–2031).",
      "By application, oil production drilling had a share of 52.1% of the market in 2025. Natural gas exploration is expected to grow with the fastest CAGR of 6.8% during the forecast period (2026–2031).",
      "By end-user, the onshore oil & gas sector had a market share of 76.3% in 2025. However, geothermal and critical-mineral exploration is expected to grow at the fastest CAGR of 8.2% through 2031.",
      "By geography, North America held a share of 43.2% of the market in 2025 and Middle East & Africa is expected to grow with a CAGR of 7.9% during the forecast period (2026–2031)."
    ],
    drivers: [
      { title: "Rising global energy demand and depletion of shallow conventional reserves", impact: "+2.1%", geo: "Global — strongest in MEA & Asia-Pacific", timeline: "Medium term (2-4 years)" },
      { title: "Unconventional resource development in shale and tight-gas plays", impact: "+1.8%", geo: "North America; Vaca Muerta (Argentina) emerging", timeline: "Short term (≤ 2 years)" },
      { title: "Automation and AI-driven drilling efficiency improvement", impact: "+1.4%", geo: "Global — early adoption in North America & Europe", timeline: "Medium term (2-4 years)" },
      { title: "National oil company capex expansion across Middle East & Africa", impact: "+1.7%", geo: "Saudi Arabia, UAE, Kuwait, Algeria, Nigeria", timeline: "Long term (≥ 4 years)" },
      { title: "Geothermal and critical-mineral land-drilling expansion", impact: "+0.7%", geo: "United States, Iceland, Australia, Kenya", timeline: "Long term (≥ 4 years)" }
    ],
    restraints: [
      { title: "Oil price volatility constraining upstream E&P capital budgets", impact: "-1.6%", geo: "Global — most acute for marginal producers", timeline: "Short term (≤ 2 years)" },
      { title: "Environmental regulations and permitting delays for new well sites", impact: "-1.1%", geo: "North America (federal lands), Western Europe", timeline: "Medium term (2-4 years)" },
      { title: "Skilled labour shortage in advanced directional drilling and automation roles", impact: "-0.8%", geo: "Global — acute in North America & MEA", timeline: "Medium term (2-4 years)" }
    ],
    segmentTables: {
      rigType: [
        { name: "Conventional Land Rigs", share: "58.3%", cagr: "4.8%", tag: "Largest" },
        { name: "Directional / Horizontal", share: "28.9%", cagr: "7.73%", tag: "Fastest" },
        { name: "Slim-Hole / Portable", share: "12.8%", cagr: "5.2%", tag: null }
      ],
      technology: [
        { name: "Top-Drive Systems", share: "44.6%", cagr: "5.1%", tag: "Largest" },
        { name: "Conventional Rotary", share: "33.1%", cagr: "3.8%", tag: null },
        { name: "Automated & Smart Drilling", share: "22.3%", cagr: "9.40%", tag: "Fastest" }
      ],
      application: [
        { name: "Oil Production Drilling", share: "52.1%", cagr: "4.9%", tag: "Largest" },
        { name: "Natural Gas Exploration", share: "31.4%", cagr: "6.80%", tag: "Fastest" },
        { name: "Geothermal & Minerals", share: "16.5%", cagr: "8.2%", tag: null }
      ]
    },
    regionTable: [
      { name: "North America", share: "43.2%", cagr: "5.1%", factors: "Permian Basin, Eagle Ford, Marcellus, Montney. US production record 13.6M bpd in 2025." },
      { name: "Middle East & Africa", share: "22.1%", cagr: "7.9%", factors: "Saudi Aramco Jafurah program (200+ wells/yr), ADNOC 5 Mbpd target, NOC capex > USD 140B." },
      { name: "Asia-Pacific", share: "18.4%", cagr: "5.8%", factors: "China Ordos & Sichuan tight-gas, India ONGC infill drilling, Australia Cooper Basin." },
      { name: "South America", share: "9.8%", cagr: "6.4%", factors: "Argentina Vaca Muerta: rig count 35 (2022) → 80+ (2025). Colombia Llanos Basin." },
      { name: "Europe", share: "6.5%", cagr: "3.2%", factors: "North Sea onshore analogues, EU energy security mandates, Eastern Europe gas drilling." }
    ],
    companyTable: [
      { name: "SLB (Schlumberger)", hq: "Houston, USA / Paris", capabilities: "MWD/LWD, Rotary Steerable Systems, Neuro™ Autonomous Drilling" },
      { name: "Halliburton Company", hq: "Houston, TX, USA", capabilities: "Drill Bits, Completions, iCruise™ Rotary Steerable, AI Optimization" },
      { name: "Baker Hughes", hq: "Houston, TX, USA", capabilities: "Top-Drive Systems, AutoTrak Curve™, HPHT Wells" },
      { name: "Nabors Industries", hq: "Hamilton, Bermuda", capabilities: "Land Rigs, RigCLOUD® Gen-5 Automation, Robotics" },
      { name: "National Oilwell Varco", hq: "Houston, TX, USA", capabilities: "Rig Equipment, Downhole Tools, Smart Drilling Technology" },
      { name: "Patterson-UTI Energy", hq: "Houston, TX, USA", capabilities: "Contract Drilling, Integrated Drilling-to-Completion Services" }
    ],
    developments: [
      { date: "January 2026", text: "Nabors Industries launched RigCLOUD® Gen-5 automated drilling platform, deployed across 62 Permian Basin land rigs, reducing average well time-to-depth by 18% versus the preceding generation." },
      { date: "November 2025", text: "Saudi Aramco awarded a multi-year onshore drilling contract worth approximately USD 3.4 billion to a Halliburton and Arabian Drilling Company consortium for the Jafurah unconventional gas program." },
      { date: "September 2025", text: "SLB commercially deployed its Neuro™ autonomous drilling solution with ADNOC on UAE tight-carbonate formations, reporting a 30% reduction in drilling non-productive time versus offset wells." },
      { date: "July 2025", text: "Patterson-UTI Energy completed integration of its NexTier Oilfield Solutions merger, creating a combined entity with 170+ active land rigs and one of North America's largest hydraulic fracturing fleets." },
      { date: "March 2025", text: "Baker Hughes introduced AutoTrak Curve™ RSS with 4.75-inch reduced outer diameter for slim onshore wellbores, targeting Eagle Ford and Bakken laterals exceeding 18,000 feet in thin reservoir intervals." }
    ],
    analysisContent: {
      overview2: "North America commands the largest share on the back of prolific Permian Basin, Eagle Ford, Haynesville, and Montney activity. The US Energy Information Administration reports US crude production at a record 13.6 million bpd in 2025 — entirely driven by unconventional land-rig campaigns. The Middle East & Africa is the fastest-growing region at 7.9% CAGR as Saudi Aramco's Jafurah program, ADNOC's capacity expansion, and sub-Saharan exploration ramp up. Automation, AI-assisted directional control, and managed-pressure drilling are reshaping cost structures across all major basins.",
      unconventionalDriver: "The United States Permian Basin accounts for approximately 27.4% of total North American rig-day demand. Average drill time-to-depth has fallen more than 35% since 2020 as lateral lengths regularly exceed 15,000 feet and real-time MWD telemetry enables continuous optimization. These gains widen the cost gap between onshore unconventionals and frontier offshore projects, channelling upstream capital toward land rigs even during softer commodity price cycles. Argentina's Vaca Muerta rig count grew from 35 in 2022 to over 80 in 2025, emerging as the hemisphere's fastest-growing unconventional play outside North America.",
      automationDriver: "Machine-learning algorithms embedded in MWD services now predict formation boundaries, optimize weight-on-bit, and reduce stick-slip vibration in real time. Halliburton's iCruise™ rotary steerable system reduces casing-point uncertainty by up to 40% in offset well comparisons. SLB's Neuro™ autonomous drilling solution, deployed with ADNOC in 2025, delivered a 30% reduction in non-productive time versus offset wells. Top-drive penetration on new land-rig builds is approaching 85%, and Nabors' RigCLOUD® Gen-5 platform — deployed across 62 Permian Basin rigs — cut average well time-to-depth by 18%.",
      rigTypeAnalysis: "Conventional land rigs maintain volume leadership at 58.3% of 2025 revenue, reflecting the vast installed base across mature basins in North America, the Middle East, and Russia. The directional and horizontal segment is the structural growth engine at 7.73% CAGR through 2031 as operators extend lateral reach in stacked-pay unconventional plays — with some Haynesville operators drilling laterals exceeding 20,000 feet to maximise reservoir contact per surface location.",
      applicationAnalysis: "Natural gas exploration is the fastest-growing application at 6.8% CAGR through 2031. LNG export capacity expansions in the United States, Qatar, and Australia are pulling forward onshore feeder-field development. The Automated & Smart Drilling segment, at 9.4% CAGR, is the fastest across all technology sub-segments as operators prioritise NPT reduction, reduced crew requirements, and integrated reservoir-to-surface data analytics.",
      northAmericaAnalysis: "North America leads global onshore drilling revenue. The US Permian Basin alone drives roughly 27% of total North American rig-day demand. Canada's Montney and Duvernay plays are maturing ahead of LNG Canada Phase 2, and Mexico's PEMEX is reopening legacy onshore fields through independent operator partnerships. US drilling services revenue was valued at approximately USD 4.0 billion in 2026.",
      meaAnalysis: "Saudi Aramco's Jafurah unconventional gas program targets more than 200 horizontal wells per year through 2030. ADNOC is pursuing 5 million bpd capacity by 2027 using advanced RSS and managed-pressure drilling in tight-carbonate reservoirs. Combined NOC capex in the region exceeded USD 140 billion in 2025. Sub-Saharan Africa — led by Nigeria, Algeria, Mozambique, and Namibia — is attracting international exploration operators, broadening the regional growth base.",
      competitiveLandscape: "The onshore drilling market is moderately consolidated at the services layer. SLB, Halliburton, and Baker Hughes dominate high-technology MWD/LWD, rotary steerable systems, and managed-pressure drilling. Contract drilling is more fragmented, led by Nabors Industries, Patterson-UTI Energy, and Precision Drilling. National oil companies in Saudi Arabia, China, and Russia operate large captive rig fleets that limit the addressable market for foreign service providers in those geographies.",
      faqs: [
        { q: "What is the size of the Global Onshore Drilling Market?", a: "The global onshore drilling market is estimated at USD 85.4 billion in 2026 and is projected to reach USD 112.6 billion by 2031, growing at a CAGR of 5.70% over the forecast period. Onshore drilling represents approximately 69.5% of total global drilling services revenue." },
        { q: "Which region has the highest growth rate in the Onshore Drilling Market?", a: "The Middle East & Africa region is expected to grow at the highest CAGR of 7.9% during the forecast period (2026–2031), driven by Saudi Aramco's Jafurah unconventional gas program, ADNOC's capacity expansion, and expanding exploration activity across sub-Saharan Africa." },
        { q: "Who are the major companies in the Onshore Drilling Market?", a: "The major companies include SLB (Schlumberger), Halliburton Company, Baker Hughes, Nabors Industries, National Oilwell Varco (NOV), Patterson-UTI Energy, Precision Drilling Corporation, and Weatherford International." },
        { q: "How much is the Onshore Drilling Market expected to grow during 2026-2031?", a: "The global onshore drilling market is expected to grow at a CAGR of 5.70% during the forecast period (2026–2031), driven by unconventional resource development, automation-led efficiency gains, and national oil company capital expenditure expansion in the Middle East and Africa." }
      ],
      scope: {
        rigType: "Conventional Land Rigs | Directional / Horizontal Rigs | Slim-Hole / Portable Rigs",
        technology: "Top-Drive Systems | Conventional Rotary | Automated & Smart Drilling",
        application: "Oil Production Drilling | Natural Gas Exploration | Geothermal & Mineral Exploration",
        power: "Up to 1,000 HP | 1,001–1,500 HP | 1,501–2,500 HP | Beyond 2,500 HP",
        geography: "North America (US, Canada, Mexico) | Middle East & Africa (Saudi Arabia, UAE, Nigeria, Algeria) | Asia-Pacific (China, India, Australia) | South America (Argentina, Brazil) | Europe",
        studyPeriod: "Historical: 2021–2025 | Forecast: 2026–2031",
        baseYear: "2025",
        currency: "USD (United States Dollar)"
      }
    },
    esgContent: {
      subtitle: "Global Onshore Drilling Market | MindEarth Research | 2024–2031",
      griFramework: [
        { series: "GRI 200 – Economic", covers: "Economic performance, anti-corruption, procurement, tax", stds: "7", relevance: "TCFD/ISSB climate financial risk; anti-bribery in NOC markets (FCPA/EITI); Pillar Two tax exposure" },
        { series: "GRI 300 – Environmental", covers: "Emissions, energy, water, biodiversity, waste", stds: "9", relevance: "GRI 305 (Scope 1–3, methane); GRI 302 (rig fuel intensity); GRI 303 (water/fracking); GRI 304 (biodiversity/TNFD)" },
        { series: "GRI 400 – Social", covers: "OHS, employment, community, human rights, diversity", stds: "16", relevance: "GRI 403 OHS (LTIR, well control, H₂S); GRI 413 (FPIC, social licence); GRI 411 (indigenous peoples)" },
        { series: "GRI 11 – Oil & Gas", covers: "Sector supplement to GRI 300/400", stds: "Sector", relevance: "Mandatory for O&G reporters; 23 material topics; benchmark under CSRD, SEC, ISSB audits" },
      ],
      regulatoryDrivers: [
        { tag: "EU CSRD", color: "bg-blue-600", desc: "GRI-aligned ESRS disclosures mandatory for large EU entities from 2025; sector-specific ESRS will incorporate GRI 11 mapping." },
        { tag: "ISSB IFRS S1/S2", color: "bg-indigo-600", desc: "Adopted in 25+ jurisdictions; elevates climate financial disclosure to mandatory with third-party assurance." },
        { tag: "SEC Climate Rule", color: "bg-amber-600", desc: "Scope 1 and 2 GHG data with third-party assurance mandatory for large accelerated US-listed filers from 2026." },
        { tag: "TNFD", color: "bg-emerald-600", desc: "Voluntary in 2023; targeted mandatory adoption in EU and UK by 2028; extends biodiversity reporting to upstream operators." },
      ],
      materialRisks: [
        { risk: "GRI 305 Emissions", pillar: "Environmental", level: "CRITICAL", levelColor: "bg-red-600", drivers: "EU ETS Phase 4; US EPA Methane Fee ($900–1,500/t); CBAM (2026); SEC Climate Rule", exposure: "ETS allowance shortfall; methane fees; CBAM tariffs; ESG capital market exclusion", detail: "Five simultaneous mechanisms create overlapping compliance obligations: EU ETS Phase 4 drives carbon prices toward €80–120/tCO₂e by 2027; US EPA Methane Emissions Reduction Program imposes fees of $900–1,500/tonne; EU Methane Regulation targets upstream O&G imports from 2030; CBAM fully operational from 2026; CSRD/ESRS E1 mandates quantified GHG disclosure." },
        { risk: "GRI 403 OHS", pillar: "Social", level: "RAPIDLY RISING", levelColor: "bg-orange-500", drivers: "EU OSH Framework 2021–27; ISO 45001; CSRD ESRS S1; OSHA enforcement", exposure: "OSHA fines up to $156K/violation; workers' comp 2–5% of payroll; class action exposure", detail: "Rig floor operations create structurally elevated OHS risk profiles. OSHA maximum willful-violation penalty stands at $156,259 per incident. Contractors with LTIRs 2–3× industry benchmark face accelerating contract disqualification from NOC tenders." },
        { risk: "GRI 201 / TCFD", pillar: "Economic", level: "CRITICAL", levelColor: "bg-red-600", drivers: "TCFD mandatory (UK, EU, NZ, Canada); ISSB IFRS S1/S2; SEC climate rule 2026–28", exposure: "WACC premium +30–60 bps for ESG laggards; CSRD fines €5–50M; stranded asset risk", detail: "ISSB IFRS S1/S2 requires companies to quantify financial impact of climate-related risks under 1.5°C, 2°C, and BAU scenarios. Stranded asset write-down risk is the highest-stakes financial exposure for onshore programs with payback periods exceeding ten years." },
        { risk: "GRI 302 Energy", pillar: "Environmental", level: "ELEVATED", levelColor: "bg-yellow-500", drivers: "EU CBAM (2026); revised EU EED; RED III (42.5% RE by 2030); EU ETS Phase 4", exposure: "CBAM tariff exposure; ETS allowance shortfall; green finance ineligibility", detail: "Rig diesel consumption — typically 50–400 gallons/day per rig — feeds directly into Scope 1 reporting. Contractors that delay fleet electrification face higher operating costs, ESG-linked contract disqualification, and ineligibility for ESG-linked credit facilities." },
      ],
      solutions: [
        { title: "Electric & Hybrid Rig Conversion", gri: "GRI 302 + GRI 305", desc: "Reduces CBAM exposure, lowers EU ETS allowance shortfall risk, qualifies for ESG-linked financing." },
        { title: "Methane Detection & Abatement", gri: "GRI 305", desc: "Addresses US EPA methane fee and EU Methane Regulation requirements for upstream operations." },
        { title: "CCUS Integration", gri: "GRI 305", desc: "Targets Scope 1 net abatement and carbon pricing risk across drilling operations." },
        { title: "AI ESG Monitoring SaaS", gri: "GRI 201 / TCFD", desc: "Supports TCFD disclosure and CSRD ESRS reporting compliance with automated data pipelines." },
        { title: "Produced Water Recycling", gri: "GRI 303", desc: "Addresses water intensity and IED effluent limits in water-stressed drilling basins." },
        { title: "OHS Digital Twin Systems", gri: "GRI 403", desc: "Real-time hazard monitoring for dropped objects, H₂S, well control and rotating machinery events." },
      ],
      kpis: [
        { n: 1, topic: "GRI 305 – Emissions", metrics: "Scope 1/2/3 GHG (tCO₂e); methane intensity (%); GHG intensity (tCO₂e/BOE); flaring intensity; net-zero pathway vs. IEA NZE" },
        { n: 2, topic: "GRI 302 – Energy", metrics: "Energy consumption — fuel + electricity (GJ); intensity (GJ/unit); renewable share (%); rig diesel consumption (gal/day)" },
        { n: 3, topic: "GRI 201 – Economic / TCFD", metrics: "Economic value generated/distributed; climate financial risk; stranded asset exposure ($B); carbon-adjusted EBITDA margin" },
        { n: 4, topic: "GRI 303 – Water", metrics: "Water withdrawal by source (m³); stressed-basin consumption; freshwater per well (M gal); produced water recycling rate" },
        { n: 5, topic: "GRI 304 – Biodiversity", metrics: "Sites in/near protected areas; well pad land disturbance (ha/well); pipeline corridor fragmentation; reclamation rate" },
        { n: 6, topic: "GRI 403 – OHS", metrics: "LTIR per million hrs; TRIR; fatality rate; process safety Tier 1/2 events; H₂S exposure incidents" },
        { n: 7, topic: "GRI 413 – Communities", metrics: "% operations with community engagement; significant negative impacts; FPIC processes; grievance resolution rate" },
        { n: 8, topic: "GRI 205 – Anti-Corruption", metrics: "Operations assessed for corruption (%); confirmed incidents; anti-corruption training coverage; EITI disclosure" },
        { n: 9, topic: "GRI 306 – Waste", metrics: "Hazardous/non-hazardous waste (tonnes); diversion rate (%); drilling cuttings per well; NORM waste handling" },
        { n: 10, topic: "GRI 401 – Employment", metrics: "Total employees by region/gender; new hires/turnover rate; benefits coverage; local hire rate at new developments" },
      ],
      investorLandscape: [
        { segment: "Sovereign Wealth Funds", examples: "Norway GPFG, ADIA, GIC", framework: "UNPRI; Net Zero AM; TCFD", criteria: "Methane intensity; Scope 1+3; GRI 11 alignment; executive ESG pay linkage", posture: "CAUTIOUS", posColor: "text-amber-600 bg-amber-50" },
        { segment: "Pension Funds", examples: "CPPIB, CalPERS, USS", framework: "IORP II; TCFD; PRI", criteria: "Climate transition plan; LTIR benchmarks; board ESG oversight; net-zero pledge", posture: "ENGAGED", posColor: "text-blue-600 bg-blue-50" },
        { segment: "ESG-Screened ETFs", examples: "iShares MSCI, SPDR S&P", framework: "MSCI ESG; Sustainalytics; FTSE4Good", criteria: "GHG intensity; water intensity; OHS score; governance", posture: "QUANTITATIVE", posColor: "text-purple-600 bg-purple-50" },
        { segment: "Green Bond Investors", examples: "ICMA GBP, EU Taxonomy, SLLs", framework: "Green Bond Principles", criteria: "Use of proceeds: electric rig, methane abatement, CCUS, geothermal", posture: "OPPORTUNITY", posColor: "text-emerald-600 bg-emerald-50" },
      ],
      benchmarks: [
        { label: "GHG Emissions", value: "85–95 Mt", unit: "CO₂e/yr (Scope 1)", sub: "Methane leakage ~30–40% on GWP-100 basis" },
        { label: "Energy Intensity", value: "0.8–1.2", unit: "GJ per BOE drilled", sub: "Rig diesel 50–400 gal/day" },
        { label: "Water per Well", value: "15–25M", unit: "gallons (Permian)", sub: "Produced water recycling avg ~55%" },
        { label: "OHS (LTIR)", value: "0.38", unit: "per 200K hrs", sub: "Best-in-class operators <0.15" },
        { label: "Land Disturbance", value: "2–5 ha", unit: "per well pad", sub: ">12,000 km new pipeline corridors/yr" },
        { label: "Compliance Cost", value: "$0.8–2.4B", unit: "annually (sector-wide)", sub: "35–40% IOC CAPEX now includes ESG prequalification" },
      ],
    },
    toc: [
      "§ SECTION I — RESEARCH FRAMEWORK",
      "1. Disclaimer & Copyright Notice",
      "2. Research Scope & Definitions",
      "2.1. Market Definition",
      "2.2. Geographic Scope & Coverage",
      "2.3. Segmentation Framework",
      "2.4. Currency, Units & Base Year Conventions",
      "3. Research Methodology",
      "3.1. Research Design & Approach",
      "3.2. Data Triangulation Process",
      "3.3. Market Size Estimation",
      "3.4. Forecast Assumptions & Limitations",
      "3.5. Abbreviations & Glossary",
      "§ SECTION II — EXECUTIVE SUMMARY & MARKET OVERVIEW",
      "4. Executive Summary",
      "4.1. Key Findings",
      "4.2. Global Market Size & CAGR Snapshot (2024–2031)",
      "4.3. Segment & Regional Highlights",
      "4.4. Competitive Landscape Highlights",
      "4.5. ESG Risk & Opportunity Summary",
      "5. Market Overview",
      "5.1. Introduction to the Global Onshore Drilling Industry",
      "5.2. Value Chain Analysis",
      "5.3. Key Industry Standards & Regulatory Frameworks",
      "5.4. Market Maturity & Technology Adoption Assessment",
      "5.5. Impact of Macroeconomic Indicators: Oil Price, E&P CAPEX & Rig Count",
      "5.6. Post-Pandemic Recovery & Supply Chain Normalization",
      "5.7. Technology Evolution in Onshore Drilling",
      "6. Market Dynamics",
      "6.1. Market Drivers",
      "6.2. Market Restraints",
      "6.3. Market Opportunities",
      "6.4. Market Challenges",
      "6.5. Porter's Five Forces Analysis",
      "6.6. PESTLE Analysis",
      "6.7. Supply Chain & Procurement Landscape Analysis",
      "§ SECTION III — MARKET SEGMENTATION",
      "7. Global Onshore Drilling Market, by Drilling Type",
      "7.1. Segment Overview & Market Share (2024–2031)",
      "7.2. Conventional Vertical Drilling",
      "7.3. Horizontal & Directional Drilling",
      "7.4. Extended Reach Drilling (ERD)",
      "7.5. Multilateral Drilling",
      "7.6. Slim-Hole & Other Drilling Types",
      "8. Global Onshore Drilling Market, by Well Purpose",
      "8.1. Segment Overview & Market Share (2024–2031)",
      "8.2. Development Wells",
      "8.3. Exploration & Appraisal Wells",
      "8.4. Workover & Re-entry Wells",
      "8.5. Geothermal & Non-O&G Wells",
      "8.6. Injection & Disposal Wells",
      "9. Global Onshore Drilling Market, by Service & Equipment Type",
      "9.1. Segment Overview & Market Share (2024–2031)",
      "9.2. Rig Equipment & Day Rates",
      "9.3. Drilling Fluids & Chemicals",
      "9.4. Wellbore Tools: Drill Bits, BHA, MWD & LWD",
      "9.5. Cementing & Completion Services",
      "9.6. Project Management & Other Oilfield Services",
      "10. Global Onshore Drilling Market, by Resource Play",
      "10.1. Segment Overview & Market Share (2024–2031)",
      "10.2. Unconventional: Shale & Tight Oil and Gas",
      "10.3. Conventional Onshore",
      "10.4. Heavy Oil & Oil Sands",
      "10.5. Coal Bed Methane (CBM)",
      "10.6. Geothermal & Other Resource Plays",
      "11. Global Onshore Drilling Market, by Operator Type",
      "11.1. Segment Overview & Market Share (2024–2031)",
      "11.2. National Oil Companies (NOCs)",
      "11.3. International Oil Companies (IOCs)",
      "11.4. Independent E&P Companies & Junior Operators",
      "11.5. Oilfield Service Companies (OFS)",
      "11.6. State Agencies & Other Operators",
      "12. Global Onshore Drilling Market, by Rig Specification",
      "12.1. Segment Overview & Market Share (2024–2031)",
      "12.2. AC Electric / Top-Drive Rigs",
      "12.3. Mechanical / SCR Rigs",
      "12.4. Automated & Hybrid Rigs",
      "12.5. Coiled Tubing Drilling Units",
      "12.6. Portable / Workover Rigs",
      "§ SECTION IV — REGIONAL ANALYSIS",
      "13. Global Onshore Drilling Market, by Region",
      "13.1. Regional Overview & Comparative Analysis (2024–2031)",
      "13.2. North America",
      "13.3. Europe",
      "13.4. Asia-Pacific",
      "13.5. MEA & Latin America",
      "§ESG SECTION V — ESG ANALYSIS",
      "§ESG 14. Environmental Performance & Emissions Profile",
      "§ESG 14.1. GHG Emissions Profile of Global Onshore Drilling Operations",
      "§ESG 14.2. Methane Leakage, Venting & Flaring Intensity by Segment",
      "§ESG 14.3. Water Consumption & Produced Water Management",
      "§ESG 14.4. Land Disturbance, Incident Frequency & Biodiversity Footprint",
      "§ESG 14.5. Environmental Performance Metrics by Segment (2026–2031)",
      "§ESG 14.6. Environmental Regulatory Compliance Landscape by Region",
      "§ESG 15. Social Performance & Human Capital",
      "§ESG 15.1. Workforce Health, Safety & LTIR Benchmarking by Operator Type",
      "§ESG 15.2. Community Engagement & Social License to Operate",
      "§ESG 15.3. Local Employment, Supply Chain Localisation & Supplier Diversity",
      "§ESG 15.4. Indigenous Peoples & Community Stakeholder Protocols",
      "§ESG 15.5. Social Performance Metrics by Segment (2026–2031)",
      "§ESG 15.6. Diversity, Equity & Inclusion in the Drilling Workforce",
      "§ESG 16. Governance, Compliance & Reporting Frameworks",
      "§ESG 16.1. Board-Level ESG Oversight & Accountability Structures",
      "§ESG 16.2. Anti-Corruption, Transparency & Whistleblower Frameworks",
      "§ESG 16.3. Regulatory Compliance Landscape by Region",
      "§ESG 16.4. ESG Data Management & Disclosure Frameworks",
      "§ESG 16.5. Governance Performance Metrics by Segment (2026–2031)",
      "§ESG 16.6. ESG-Linked Financing & Shareholder Engagement",
      "§ESG 17. Transition Risk, Physical Risk & Revenue Exposure",
      "§ESG 17.1. Stranded Asset Risk Assessment by Drilling Type & Resource Play",
      "§ESG 17.2. Carbon Pricing Impact by Operator Type & Region",
      "§ESG 17.3. ESG Risk Exposure: Revenue at Risk by Segment (2026–2031)",
      "§ESG 17.4. Transition Risk vs. Physical Risk: Comparative Assessment",
      "§ESG 17.5. Regulatory & Litigation Risk Index by Geography",
      "§ESG 17.6. Scenario Analysis: 1.5°C, 2°C & Business-as-Usual Pathways",
      "§ESG 18. ESG Solutions Adoption & Technology Transition",
      "§ESG 18.1. Electric & Hybrid Rig Adoption Rates by Region & Operator Type",
      "§ESG 18.2. Methane Detection, Quantification & Leak Abatement Technologies",
      "§ESG 18.3. Carbon Capture & Storage (CCS) Integration in Drilling Operations",
      "§ESG 18.4. AI-Powered Emissions Monitoring & Digital ESG Reporting Platforms",
      "§ESG 18.5. ESG Solutions Adoption Rate by Segment (2026–2031)",
      "§ESG 18.6. Barriers to ESG Technology Adoption in the Onshore Drilling Sector",
      "§ESG 19. Financial Impact, Market Opportunity & ESG-Driven Expansion",
      "§ESG 19.1. ESG-Driven CAPEX Reallocation in the Global Drilling Sector",
      "§ESG 19.2. Decarbonization Technologies: Addressable Market Sizing (2025–2031)",
      "§ESG 19.3. Financial Impact of ESG Compliance by Segment (2026–2031)",
      "§ESG 19.4. ESG-Driven Market Expansion Segments (2026–2031)",
      "§ESG 19.5. Geothermal Drilling as an ESG-Aligned Growth Adjacency",
      "§ESG 19.6. Impact of ESG Scores on Contract Awards & Market Valuation",
      "§ESG 19.7. ESG Opportunity Sizing: Total Quantified Market Potential (2025–2031)",
      "§ESG 20. ESG Integration & Investor Landscape",
      "§ESG 20.1. Overview: ESG as a Driver of Capital Allocation in Upstream Energy",
      "§ESG 20.2. Institutional Investor Landscape",
      "§ESG 20.3. Retail & Private Investor Landscape",
      "§ESG 20.4. ESG Disclosure Quality & Its Influence on Cost of Capital",
      "§ESG 20.5. Investor Risk Scorecard by Segment",
      "§ESG 20.6. ESG-Linked Return Premium Analysis (2019–2024)",
      "§ESG 20.7. Emerging Frameworks: ISSB IFRS S1 & S2, TNFD",
      "§ESG 20.8. Investment Opportunity Sizing in ESG-Aligned Drilling Segments (2025–2031)",
      "§ SECTION VII — COMPETITIVE LANDSCAPE & COMPANY PROFILES",
      "21. Competitive Landscape",
      "21.1. Market Share Analysis (2024)",
      "21.2. Competitive Strategies",
      "21.3. Competitive ESG Positioning & Heat Map",
      "21.4. Recent Developments (2022–2024)",
      "21.5. Strategic Partnerships & Alliances",
      "22. Company Profiles",
      "22.1. Schlumberger (SLB)",
      "22.2. Halliburton Company",
      "22.3. Baker Hughes Company",
      "22.4. Nabors Industries Ltd.",
      "22.5. Patterson-UTI Energy",
      "22.6. Helmerich & Payne, Inc.",
      "22.7. Parker Drilling Company",
      "22.8. KCA Deutag Drilling",
      "22.9. Weatherford International",
      "22.10. China Oilfield Services Limited (COSL)",
      "22.11. ADES International Holding",
      "22.12. Calfrac Well Services",
      "§ SECTION VIII — APPENDIX",
      "23. Appendix",
      "23.1. List of Tables",
      "23.2. Data Sources: Primary Research",
      "23.3. Data Sources: Secondary Research",
      "23.4. ESG Data Sources & Frameworks Referenced",
      "23.5. About MindEarth",
      "23.6. Report Customisation Options",
    ],
  },
];

export const clientLogos = ["Tata Group", "Sumitomo", "Circle K", "Danone", "Infosys", "Mahindra", "Kuwait Investment Authority", "Asian Dev. Bank"];

export function getReportBySlug(slug) {
  return reports.find((r) => r.slug === slug) || null;
}
